# version 3+ does different things re: networking from 2.x
# mainly things to support swarms
# aka things we don't need/want
version: '2.4'
services:
  fishblog-app:
    container_name: fishblog-app
    # for development, build the image
    image: ghcr.io/wetfish/blog:dev
    build: .
    # restart unless we stopped it manually
    restart: unless-stopped
    # our config file
    volumes:
      - "./config.js:/app/server/config.js:ro"
      - "./uploads:/app/static/uploads:ro"
    # normally behind centeral traefik defined in production-manifests/services/traefik
    ports:
      - "127.0.0.1:2304:2304"
