# version 3+ does different things re: networking from 2.x
# mainly things to support swarms
# aka things we don't need/want
version: '2.4'
services:
  # webservice
  #
  fishblog-app:
    container_name: fishblog-app
    # production: track "prod" tag on ghcr.io
    # image: ghcr.io/wetfish/blog:prod
    # for development, build the image
    # TODO: once ghcr.io autobuilds in place, change this
    build: .
    
    # restart unless we stopped it manually
    restart: unless-stopped

    # uncomment to expose port directly
    # normally behind centeral traefik defined in production-manifests/services/traefik
    # ports:
    #   - "2304:2304"

    # our config file
    volumes:
      - "./config.js:/app/server/config.js:ro"

    # join both the internal-to-this-stack network and the traefik backend network
    networks:
      traefik-backend: {}
  #
  # end webservice


networks:
  # persistent, externally created
  traefik-backend:
    external: true
