# version 3+ does different things re: networking from 2.x
# mainly things to support swarms
# aka things we don't need/want
version: '2.4'
services:
  fishblog-app:
    # production: track "prod" tag on ghcr.io
    # image: ghcr.io/wetfish/blog:prod
    # for development, build the image
    build: .
    restart: unless-stopped
    env_file: 
      - web.env
    # uncomment to expose port directly
    # normally behind centeral traefik defined in services/traefik
    # ports:
    #   - "2304:2304"
    volumes:
      - "./config.js:/app/server/config.js:ro"
    networks:
      fishblog-internal: {}
      traefik-backend: {}

  fishblog-db:
    image: docker.io/mariadb:10.10.2
    restart: unless-stopped
    env_file:
      - mariadb.env
    # built-in healthcheck script
    healthcheck:
      test: ["healthcheck.sh", "--su=mysql", "--connect", "--innodb_initialized"]
      interval: 60s
      timeout: 5s
      retries: 5
    # mysql data and socket/pid dirs
    volumes:
      - "./db/data:/var/lib/mysql:rw"
      - "./db/run:/var/run/mysqld:rw"
    networks:
      fishblog-internal: {}

networks:
  fishblog-internal:
    name: fishblog-internal
    driver: bridge
  traefik-backend:
    external: true
